#!/bin/bash

echo "🚀 Vivek Prajapati Portfolio Deployment Guide"
echo "=============================================="
echo ""
echo "Your portfolio has been built successfully!"
echo "Build folder location: $(pwd)/build"
echo ""
echo "📋 DEPLOYMENT OPTIONS:"
echo ""
echo "1. 🎯 DRAG & DROP (Easiest - 2 minutes):"
echo "   - Go to https://netlify.com"
echo "   - Sign up/Login"
echo "   - Drag the 'build' folder to the deployment area"
echo "   - Your site will be live instantly!"
echo ""
echo "2. 📦 GITHUB + NETLIFY (Best for updates):"
echo "   a) Create a new repository on GitHub named 'vivek-portfolio'"
echo "   b) Run these commands:"
echo "      git remote add origin YOUR_GITHUB_REPO_URL"
echo "      git push -u origin main"
echo "   c) Connect the GitHub repo to Netlify for auto-deployments"
echo ""
echo "3. 🌐 STATIC FILE HOSTING:"
echo "   - Upload the 'build' folder contents to any static hosting service"
echo "   - Examples: Vercel, GitHub Pages, Firebase Hosting"
echo ""
echo "✨ Your portfolio includes:"
echo "   - Professional Android Developer showcase"
echo "   - Glassmorphic background animations"
echo "   - Mobile-responsive design"
echo "   - Modern React components"
echo ""
echo "🔗 After deployment, share your portfolio URL with employers!"
