name: CI/CD Pipeline - Portfolio

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Job 1: Run tests and code quality checks
  test:
    runs-on: ubuntu-latest
    name: Test & Code Quality
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint
      run: npm run lint --if-present || npx eslint src --ext .js,.jsx,.ts,.tsx --max-warnings 0
      continue-on-error: false
    
    - name: Run Tests
      run: npm test -- --coverage --watchAll=false --passWithNoTests
      env:
        CI: true
    
    - name: Upload test coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
    
    - name: Test Build
      run: npm run build
      env:
        PUBLIC_URL: /portfolio

  # Job 2: Build and deploy (only on main/master push)
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    needs: test
    # Only run on push to main/master (not on PRs)
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: read
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
      env:
        PUBLIC_URL: /portfolio
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './build'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
